### ISSUE TITLE
yarn install not working

### ISSUE THREAD

**Issue by cateiru** [zeddz92/react-emoji-search#9]
Hi!

When I try to install this package using yarn, the installation fails with an error.

```bash
 » yarn add react-emoji-search
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@chakra-ui/react > @chakra-ui/theme@2.1.10" has unmet peer dependency "@chakra-ui/styled-system@>=2.0.0".
warning "@chakra-ui/react > @chakra-ui/theme > @chakra-ui/theme-tools@2.0.11" has unmet peer dependency "@chakra-ui/styled-system@>=2.0.0".
warning "@emotion/react > @emotion/babel-plugin@11.10.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/react > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @typescript-eslint/eslint-plugin@5.36.2" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
warning " > eslint-plugin-prettier@4.2.1" has unmet peer dependency "prettier@>=2.0.0".
warning "react-emoji-search > tailwindcss@3.2.4" has unmet peer dependency "postcss@^8.0.9".
warning " > react-emoji-search@2.2.25" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning " > react-emoji-search@2.2.25" has incorrect peer dependency "react-dom@^16.8.0 || ^17.0.0".
[4/4] Building fresh packages...
[1/2] ⠁ core-js-pure
error /home/user/repositories/repo/node_modules/react-emoji-search: Command failed.
Exit code: 1
Command: npx npm-force-resolutions
Arguments:
Directory: /home/user/repositories/repo/node_modules/react-emoji-search
Output:
Error: ENOENT: no such file or directory, open './package-lock.json'
    at Object.openSync (node:fs:585:3)
    at Object.fs [as readFileSync] (node:fs:453:35)
    at npm_force_resolutions$core$node_slurp (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:15:20)
    at npm_force_resolutions$core$read_json (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:22:23)
    at switch__2144__auto__ (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3)
    at /home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:151:3
    at npm_force_resolutions$core$update_package_lock_$_state_machine__2145__auto____1 (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:648:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:664:88)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped (/home/user/.npm/_npx/73b02210abc194ff/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
```

`preinstall` runs on package install and runs `npx npm-force-resolutions`. However, it seems that the `package-lock.json` does not exist in the directory installed from npm, causing an error.

I haven't tested it, but you can probably get the same error with npm i.
Hiding the error it like below should solve it.

```json
"preinstall": "npx npm-force-resolutions || echo 'ignore'"
```

**Comment by zeddz92** [comment]
Hi @cateiru , you are right, the issue was on the preinstall script. I removed it and also updated all dependencies and tested installing it with create-react-app and next.js using the latest version on react. Let me know if it's working now.

**Comment by cateiru** [comment]
Thanks @zeddz92 !

I have confirmed that it can be installed. Thanks for the quick fix!
